<?php
require_once("config.php");
if(isset($_POST['form_submit'])){
$name=trim($_POST['name']);
$fname=trim($_POST['fname']);
$mname=trim($_POST['mname']);
$gender=trim($_POST['gender']);
$dob=trim($_POST['dob']);
$address=trim($_POST['address']);    
$category=trim($_POST['category']);
$course=trim($_POST['course']);
$email=trim($_POST['email']);
$mobile=trim($_POST['mobile']);
$pay_status='PAID';
$course_fees='6000';
$res_no='TS'.rand(99,100).time();
$folder="uploads/";
//Photo   
$image_file=$_FILES['image']['name'];
$file=$_FILES['image']['tmp_name'];
$path=$folder.$image_file;
$file_name_array=explode(".",$image_file);
$extension=end($file_name_array);
$new_image_name='photo_'.rand().'.'.$extension;
//Sign   
$simage_file=$_FILES['simage']['name'];
$sfile=$_FILES['simage']['tmp_name'];
$spath=$folder.$simage_file;
$file_name_array=explode(".",$simage_file);
$extension=end($file_name_array);
$snew_image_name='sign_'.rand().'.'.$extension;
}
?>